// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Prisma 7 dropped the schema-level `directUrl` field — the CLI (migrate, studio,
    // seed) now just uses whatever `url` resolves to here. Point it at the session
    // pooler, not DATABASE_URL's transaction pooler, since migrations run DDL that
    // transaction-mode pgbouncer doesn't handle well. The running app still reads
    // DATABASE_URL directly (see src/lib/prisma.ts), independent of this file.
    url: process.env["DIRECT_URL"],
  },
});
